name: heronsvote
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  step_progress: ^2.7.0
  
  # For Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.4.4
  iconify_flutter: ^0.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  pin_code_fields: ^8.0.1

  # For file opener
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.4
  read_pdf_text: ^0.3.1

  # For camera hehe
  camera: ^0.11.0+1
  image: ^4.5.4

  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_commons: ^0.11.0

  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google_logo.png
    - assets/HeronVoteLogo.png
    - assets/HeronsVoteText.png
    - assets/BackButton.png
    - assets/error.svg
    - assets/verified.svg
    - assets/verify.svg
    - assets/back.svg
  fonts:  
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600