// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOXynjC4MVIwbpz67DsJLdWS0RCXk7bY',
    appId: '1:510958334373:web:30058b8235281b084cf84c',
    messagingSenderId: '510958334373',
    projectId: 'heronsvote',
    authDomain: 'heronsvote.firebaseapp.com',
    storageBucket: 'heronsvote.firebasestorage.app',
    measurementId: 'G-2VFRY4RN46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdbN8VZ_bkOO1juILUoFP5fQ1gtg2p70',
    appId: '1:510958334373:android:4c1adb6206b0a2774cf84c',
    messagingSenderId: '510958334373',
    projectId: 'heronsvote',
    storageBucket: 'heronsvote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SEkoUbi5j9M2DdVNlV1rLmtrcqoNSZE',
    appId: '1:510958334373:ios:ebee863a668e62e84cf84c',
    messagingSenderId: '510958334373',
    projectId: 'heronsvote',
    storageBucket: 'heronsvote.firebasestorage.app',
    iosBundleId: 'com.example.heronsvote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5SEkoUbi5j9M2DdVNlV1rLmtrcqoNSZE',
    appId: '1:510958334373:ios:ebee863a668e62e84cf84c',
    messagingSenderId: '510958334373',
    projectId: 'heronsvote',
    storageBucket: 'heronsvote.firebasestorage.app',
    iosBundleId: 'com.example.heronsvote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbOXynjC4MVIwbpz67DsJLdWS0RCXk7bY',
    appId: '1:510958334373:web:c3f6714d375ad5184cf84c',
    messagingSenderId: '510958334373',
    projectId: 'heronsvote',
    authDomain: 'heronsvote.firebaseapp.com',
    storageBucket: 'heronsvote.firebasestorage.app',
    measurementId: 'G-B4C0D2MDH9',
  );
}
